name: KittyMark CI

on:
  pull_request:
    branches: [ "dev" ]

jobs:
  client-ci:
    if: contains(github.event.pull_request.labels.*.name,'🎨 FE')
    name: client-ci
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Build client
        working-directory: client
        run: |
          npm ci
          npm run build

      - name: Run linters
        uses: wearerequired/lint-action@v2
        with:
          eslint: true
          prettier: true

  server-ci:
    if: contains(github.event.pull_request.labels.*.name,'💻 BE')
    name: server-ci
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Build server
        working-directory: server
        run: |
          npm ci
          npm run build

      - name: Run linters
        uses: wearerequired/lint-action@v2
        with:
          eslint: true
          prettier: true
