name: KittyMark CI

on:
  pull_request:
    branches: [ "dev" ]
# Down scope as necessary via https://docs.github.com/en/actions/security-guides/automatic-token-authentication#modifying-the-permissions-for-the-github_token
permissions:
  checks: write
  contents: write

jobs:
  client-ci:
    if: contains(github.event.pull_request.labels.*.name,'🎨 FE')
    name: client-ci
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          # Make sure the actual branch is checked out when running on pull requests
          ref: ${{ github.head_ref }}

      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Build client
        working-directory: client
        run: |
          npm ci
          npm run build

      - name: Run linters
        uses: wearerequired/lint-action@v2
        with:
          eslint: true
          prettier: true

  server-ci:
    if: contains(github.event.pull_request.labels.*.name,'💻 BE')
    name: server-ci
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Build server
        working-directory: server
        run: |
          npm ci
          npm run build

      - name: Run linters
        uses: wearerequired/lint-action@v2
        with:
          eslint: true
          prettier: true
